server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/article?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 12345
  activemq:
    broker-url: tcp://148.70.202.70:61616
mybatis:
  type-aliases-package: com.weilianda.pojo
  mapper-locations: classpath:com/weilianda/mapper/*.xml